dataset_name: "cifar10"
dataset_path: "../datasets/cifar10"
model_type: "cnn"
output_path: "../../storage/produced-data/logs/cifar10/cnn/only_mlu/"
image_shape: !!python/tuple [32, 32]
dataset_type: c
data_type: "float32"
max_value: 255
label_count: 10
batch_size: 64
learning_rate: 0.1
loss: "categorical_crossentropy"
metrics: ["accuracy"]
max_iterations: 100
client_count: 100
quantification_flag: False
quantification_options: {"dtype": np.float16}
more_local_updates_flag: True
more_local_updates_options: {"local_iterations": 50}
sparsification_flag: False
sparsification_options: {"percentile": 80}
