dataset_name: "colorectal"
dataset_path: "../datasets/colorectal"
model_type: "vgg16"
output_path: "../../storage/produced-data/logs/final_run/colorectal/vgg16/"
image_shape: !!python/tuple [150, 150]
data_type: "float32"
max_value: 255
label_count: 8
batch_size: 64
learning_rate: 0.001
loss: "categorical_crossentropy"
metrics: ["accuracy"]
max_iterations: 125
client_count: 5
quantification_flag: False
quantification_options: {"dtype": np.float16}
more_local_updates_flag: True
more_local_updates_options: {"local_iterations": 20}
sparsification_flag: False
sparsification_options: {"percentile": 80}
dataset_type: c
